#!/usr/bin/env bash

# Install ansible
sudo apt update && sudo apt -y upgrade
sudo apt install -y software-properties-common
#sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install -y ansible
# Configure the new system
ansible-playbook $HOME/ansible/local.yml --ask-become-pass --ask-vault-pass


