- hosts: localhost
  become: true
  pre_tasks:
  - name: Update cache
    apt:
      update_cache: yes
      upgrade: dist 
    tags:
      - always
  - import_tasks: tasks/core.yml
  - import_tasks: tasks/ssh.yml
  - import_tasks: tasks/dotfiles.yml
  - import_tasks: tasks/zsh.yml
  - import_tasks: tasks/pyenv.yml
  - import_tasks: tasks/gnome.yml
  - import_tasks: tasks/neovim.yml
  - import_tasks: tasks/docker.yml
  # - import_tasks: tasks/vscode.yml
