- name: alacritty ppa
  apt_repository:
   repo: ppa:aslatter/ppa
   state: present
   update_cache: true
  tags:
    - alacritty
- name: Install alacritty
  apt:
    name=alacritty
  tags:
    - alacritty
- name: Install alacritty themes
  file:
    path: $HOME/.config/alacritty/themes
    state: directory
- name: Install alacritty themes
  ansible.builtin.git:
    repo: 'https://github.com/alacritty/alacritty-theme'
    dest: "{{ lookup('env', 'HOME') }}/.config/alacritty/themes"
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - alacritty

