- name: Install System Packages 1 (build-essential)
  become: true
  apt:
    name: ["build-essential", "ripgrep", "fd-find" ]
  tags:
    - core

- name: Install System Packages 2 (the rest)
  become: true
  apt:
    name: [ "curl", "git" ]
  tags:
    - core
