- name: Install core packages
  become: true
  vars:
    dev_base: "{{ 'build-essential' if ansible_distribution in ['Debian', 'Ubuntu'] else 'base-devel' }}"
    fd: "{{ 'fd-find' if ansible_distribution in ['Debian', 'Ubuntu'] else 'fd' }}"
    crc32: "{{ 'libarchive-zip-perl' if ansible_distribution in ['Debian', 'Ubuntu'] else 'perl-archive-zip' }}"
  package:
    name: 
    - "ripgrep"
    - "curl"
    - "git"
    - "fzf"
    - "tldr"
    - "unzip"
    - "{{ dev_base }}"
    - "{{ fd }}"
    - "{{ crc32 }}"
    - xclip # needed by neovim to clipboard copy when xserver is active
    - "{{ 'wl-clipboard' if ansible_distribution == 'Archlinux' else '' }}" # wayland clipboard, in wsl is the only option for arch to copy to system clipboard
    - "{{ 'tree' if ansible_distribution == 'Archlinux' else '' }}"
    - "{{ 'man-db' if ansible_distribution == 'Archlinux' else '' }}"
    - "{{ 'man-pages' if ansible_distribution == 'Archlinux' else '' }}"
    - kitty
    - bat
    - jq
  tags:
    - core
    - wsl

