- name: Install packages
  apt:
    name: [ "build-essential", "ripgrep", "fd-find", "curl", "git", "tmux", "fzf", "tldr", "neofetch" ]
  tags:
    - core
    - ubuntu
    - wsl
- name: Install utils
  apt:
    name: [ "libarchive-zip-perl" ] # for CRC32
  tags:
    - core
    - ubuntu
    - wsl

