- name: Install packages
  become: true
  apt:
    name: [ "build-essential", "ripgrep", "fd-find", "curl", "git", "tmux", "fzf", "tldr", "neofetch", "picom" ]
  tags:
    - core
    - ubuntu
    - wsl
- name: Install utils
  become: true
  apt:
    name: [ "libarchive-zip-perl" ] # for CRC32
  tags:
    - core
    - ubuntu
    - wsl

