- name: Install packages to allow apt to use a repository over HTTPS
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  tags:
    - docker
    - wsl
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Add Docker’s official GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker
    - wsl
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Set up the Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  tags:
    - docker
    - wsl
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install Docker Engine
  become: true
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  tags:
    - docker
    - wsl
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install Docker
  become: true
  pacman: 
    name:
    - docker
    - cni-plugins
  tags:
    - docker
    - wsl
  when: ansible_distribution in ["Archlinux"]

- name: Ensure Docker service is running
  become: true
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker
    - wsl

- name: Add the current user to the Docker group
  become: true
  user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: yes
  tags:
    - docker
    - wsl

