- name: Install stow
  become: true
  package: name=stow
  tags:
    - stow
    - dotfiles
    - wsl
- name: Ensure SSH client is installed on Arch Linux
  become: true
  pacman:
    name: openssh
    state: present
  tags:
    - stow
    - dotfiles
    - wsl
  when: ansible_distribution == "Archlinux"
- name: Cloning dotfiles
  git:
    repo: 'git@github.com:amahran/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
    force: yes
  environment:
    GIT_SSH_COMMAND: "ssh -i {{ lookup('env', 'HOME') }}/.ssh/personal_github"
  tags:
    - stow
    - dotfiles
    - wsl
- name: Stow dotfiles
  shell: cd {{ lookup('env', 'HOME') }}/.dotfiles && ./ubuntu
  tags:
    - stow
    - dotfiles
    - wsl

