- name: Install stow
  apt: name=stow
  tags:
    - stow
    - dotfiles
    - ubuntu
    - wsl
- name: Cloning dotfiles
  git:
    repo: 'https://github.com/amahran/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - stow
    - dotfiles
    - ubuntu
    - wsl
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - stow
    - dotfiles
    - ubuntu
    - wsl

