- name: Install extra packages - 1
  become: true
  package:
    name: 
    - fastfetch
    - reflector
    - speedtest-cli
    - erofs-utils
    # Fonts
    - otf-firamono-nerd
    - ttf-jetbrains-mono-nerd
    - noto-fonts
    - noto-fonts-cjk
    - noto-fonts-extra
    - ttf-dejavu
  when: ansible_distribution in ["Archlinux"]
  tags:
    - extra
    - wsl

- name: Install extra packages - 2
  become: true
  package:
    name: 
    - obsidian
    - zathura
    - zathura-pdf-mupdf
    - remmina
    - libreoffice-fresh
    - tesseract-data-deu
    - gnome-themes-extra
    - fwupd
    - geoclue
    # VPN
    - networkmanager-l2tp
    - strongswan
    # For ipu6 laptop webcam
    - gst-plugin-libcamera
    - libcamera
    - pipewire-libcamera
    # Blutooth
    - bluez
    - bluez-utils
  when: ansible_distribution in ["Archlinux"]
  tags:
    - extra

- name: Install AUR extra packages - 1
  command: paru -S --needed --noconfirm noto-fonts-ar ocrmypdf dosfstools # srecord (not working with gcc 15)
  when: ansible_distribution in ["Archlinux"]
  tags:
    - extra
    - wsl

- name: Install AUR extra packages - 2
  command: paru -S --needed --noconfirm flameshot-git
  when: ansible_distribution in ["Archlinux"]
  tags:
    - extra

- name: Create custom reflector config
  become: true
  copy:
    dest: /etc/xdg/reflector/reflector.conf
    content: |
      --country Germany
      --age 12
      --protocol https
      --sort rate
      --save /etc/pacman.d/mirrorlist
    mode: '0644'
  when: ansible_distribution in ["Archlinux"]
  tags:
    - extra
    - reflector
    - wsl

- name: Enable and start system services - 1
  become: true
  service:
    name: reflector.timer
    enabled: true
    state: started
  when: ansible_distribution in ["Archlinux"]
  tags:
    - extra
    - reflector
    - wsl

- name: Enable and start system services - 2
  become: true
  vars:
    services:
      - bluetooth
      - systemd-resolved
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ services }}"
  when: ansible_distribution in ["Archlinux"]
  tags:
    - extra

- name: Symlink /etc/resolv.conf to systemd's stub
  become: true
  file:
    src: ../run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  when: ansible_distribution in ["Archlinux"]
  tags:
    - extra

