- name: i3 - install
  become: true
  apt:
    name: [ "i3", "feh", "pavucontrol", "autorandr" ]
  tags:
    - gnome
    - ubuntu
- name: i3 - configure
  command: "gsettings set org.gnome.desktop.sound event-sounds false"
  tags:
    - gnome
    - ubuntu
- name: Get xterm theme
  ansible.builtin.git:
    repo: 'https://github.com/rose-pine/gnome-terminal.git'
    dest: "{{ lookup('env', 'HOME') }}/.config/xterm/themes"
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - gnome
    - ubuntu
- name: Set xterm theme
  shell: dconf load /org/gnome/terminal/legacy/profiles:/ < $HOME/.config/xterm/themes/dist/rose-pine.dconf
  tags:
    - gnome
    - ubuntu
