- name: Install hyprland utils - 1
  become: true
  package:
    name: 
    - "rofi-wayland"
    - "waybar"
    - "hyprlock"
    - "hypridle"
    - "hyprpaper"
    - "swaync"
    - "brightnessctl"
    - "kanshi"
    - "hyprpolkitagent"
  when: ansible_distribution in ["Archlinux"]
  tags:
    - hyprland

- name: Install AUR packages
  kewlfft.aur.aur:
    name: 
    - hyprshot
    - pwvucontrol
    - blueberry-wayland
    use: paru
    state: present
  when: ansible_distribution in ["Archlinux"]
  tags:
    - hyprland

- name: Enable and start polkit auth agent
  systemd:
    name: 
    - hyprpolkitagent
    enabled: true
    state: started
    user: true
  when: ansible_distribution in ["Archlinux"]
  tags:
    - hyprland

