- name: Install hyprland utils - 1
  become: true
  package:
    name: 
    - "rofi-wayland"
    - "waybar"
    - "hyprlock"
    - "hypridle"
    - "hyprpaper"
    - "swaync"
    - "brightnessctl"
    - "kanshi"
    - "hyprpolkitagent"
  when: ansible_distribution in ["Archlinux"]
  tags:
    - hyprland

- name: Install AUR packages
  kewlfft.aur.aur:
    name: 
    - hyprshot
    - pwvucontrol
    use: paru
    state: present
  when: ansible_distribution in ["Archlinux"]
  tags:
    - hyprland

# - name: Install hyprland utils - 2
#   command: yay -S --noconfirm hyprshot
#   when: ansible_distribution in ["Archlinux"]
#   tags:
#     - hyprland
#
