- name: Neovim - Install dependencies
  become: true
  package: 
    name:
      - base-devel
      - cmake
      - unzip
      - ninja
      - curl
      - tree-sitter-cli
      # neovim plugins uses those
      - npm
      - luarocks
      - ruby
      - yarn
      - deno
      - webkit2gtk
      # TODO: add this for debain
      - "{{ 'python-neovim' if ansible_distribution == 'Archlinux' else '' }}"
  tags:
    - neovim
    - wsl
- name: Install npm neovim
  become: true
  shell: npm install -g neovim
  tags:
    - neovim
    - wsl
- name: Remove neovim
  become: true
  file:
    path: "{{ lookup('env', 'HOME') }}/neovim"
    state: absent
  when: ansible_distribution in ["Ubuntu"]
  tags:
    - neovim
    - wsl
- name: Clone Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "/tmp/neovim"
    version: master
  when: ansible_distribution in ["Ubuntu"]
  tags:
    - neovim
    - wsl
- name: Build neovim
  shell: "cd /tmp/neovim && make CMAKE_BUILD_TYPE=Release"
  when: ansible_distribution in ["Ubuntu"]
  tags:
    - neovim
    - wsl
- name: Install neovim
  become: true
  shell: "cd /tmp/neovim && make install"
  when: ansible_distribution in ["Ubuntu"]
  tags:
    - neovim
    - wsl
- name: Install neovim
  become: true
  package: name=neovim
  when: ansible_distribution in ["Archlinux"]
  tags:
    - neovim
    - wsl
