- name: Neovim - Install dependencies
  become: true
  package: 
    name:
      - cmake
      - npm # this is needed for installing some treesitter plugins
  tags:
    - neovim
    - wsl
- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - neovim
    - wsl
- name: Clone Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - neovim
    - wsl
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
  tags:
    - neovim
    - wsl
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - neovim
    - wsl
