- name: Neovim - Install dependencies
  become: true
  package: 
    name:
      - base-devel
      - cmake
      - unzip
      - ninja
      - curl
      - tree-sitter-cli
      # neovim plugins uses those
      - npm
      - luarocks
      - ruby
      # TODO: add this for debain
      - "{{ 'python-neovim' if ansible_distribution == 'Archlinux' else '' }}"
  tags:
    - neovim
    - wsl
- name: Install npm neovim
  become: true
  shell: npm install neovim
  tags:
    - neovim
    - wsl
- name: Clone Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
    update: yes
  tags:
    - neovim
    - wsl
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=Release"
  tags:
    - neovim
    - wsl
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - neovim
    - wsl
