- name: Clone paru repository
  git:
    repo: https://aur.archlinux.org/paru.git
    dest: /tmp/paru
    update: yes
  when: ansible_distribution in ["Archlinux"]
  tags:
    - paru
    - wsl

- name: Build and install paru
  shell: makepkg -si --noconfirm
  args:
    chdir: /tmp/paru
  when: ansible_distribution in ["Archlinux"]
  tags:
    - paru
    - wsl

- name: Clean up paru build directory
  become: true
  file:
    path: /tmp/paru
    state: absent
  when: ansible_distribution in ["Archlinux"]
  tags:
    - paru
    - wsl

