- name: Ensure .ssh directory exists.
  file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh/"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh
    - wsl
- name: Install ssh key
  copy:
    src: .ssh/
    dest: "{{ lookup('env', 'HOME') }}/.ssh/"
    mode: 0600
  tags:
    - dotfiles
    - ssh
    - wsl
- name: Set authorized key taken from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  tags:
    - dotfiles
    - ssh
    - wsl
# - name: Debug - List .pub files
#   debug:
#     msg: "{{ lookup('fileglob', '/home/alaa/.ssh/*.pub', wantlist=True) }}"
#   tags:
#     - dotfiles
#     - ssh
#     - wsl

