- name: Ensure .ssh directory exists.
  file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh/"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key
  copy:
    src: .ssh/
    dest: "{{ lookup('env', 'HOME') }}/.ssh/"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Set authorized key taken from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  tags:
    - dotfiles
    - install
    - ssh
