- name: Ensure .ssh directory exists.
  become: no
  file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh/"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh
    - ubuntu
    - wsl
- name: Install ssh key
  become: no
  copy:
    src: .ssh/
    dest: "{{ lookup('env', 'HOME') }}/.ssh/"
    mode: 0600
  tags:
    - dotfiles
    - ssh
    - ubuntu
    - wsl
- name: Set authorized key taken from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  tags:
    - dotfiles
    - ssh
    - ubuntu
    - wsl
- name: Debug - List .pub files
  debug:
    msg: "{{ lookup('fileglob', '/home/alaa/.ssh/*.pub', wantlist=True) }}"
  tags:
    - dotfiles
    - ssh
    - ubuntu
    - wsl

