- name: Utils - Install packages
  become: true
  apt:
    name: [ "neofetch", "feh", "pavucontrol", "autorandr" ]
  tags:
    - utils
- name: Utils - Configure system
  become: true
  command: "gsettings set org.gnome.desktop.sound event-sounds false"
  tags:
    - utils