- name: Install Virtual Machine tools
  become: true
  package:
    name: 
    - "libvirt"
    - "qemu-full"
    - "virt-manager"
    - "virt-viewer"
    - "dnsmasq"
    - "edk2-ovmf"
    - "dmidecode"
  when: ansible_distribution in ["Archlinux"]
  tags:
    - virt

- name: Enable and start libvirtd service
  become: true
  service:
    name: libvirtd
    enabled: true
    state: started
  when: ansible_distribution in ["Archlinux"]
  tags:
    - virt

- name: Add user to libvirt group
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: libvirt
    append: yes
  when: ansible_distribution in ["Archlinux"]
  tags:
    - virt
