- name: Clone yay repository
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    update: yes
  when: ansible_distribution in ["Archlinux"]
  tags:
    - yay
    - wsl

- name: Build and install yay
  shell: makepkg -si --noconfirm
  args:
    chdir: /tmp/yay
  when: ansible_distribution in ["Archlinux"]
  tags:
    - yay
    - wsl

- name: Clean up yay build directory
  become: true
  file:
    path: /tmp/yay
    state: absent
  when: ansible_distribution in ["Archlinux"]
  tags:
    - yay
    - wsl

