---
- name: Download the latest Zoom package
  get_url:
    url: https://zoom.us/client/latest/zoom_amd64.deb
    dest: /tmp/zoom_latest.deb
  tags:
    - zoom
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install the downloaded Zoom package
  become: yes
  apt:
    deb: /tmp/zoom_latest.deb
    update_cache: yes
    force: yes
  tags:
    - zoom
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Remove the downloaded package
  file:
    path: /tmp/zoom_latest.deb
    state: absent
  tags:
    - zoom
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install zoom
  kewlfft.aur.aur:
    name: zoom
    use: yay
    state: present
  tags:
    - zoom
  when: ansible_distribution in ["Archlinux"]

