- name: Install zsh
  become: true
  apt: name=zsh
  tags:
    - zsh
    - ubuntu
    - wsl
- name: Change shell
  become: true
  shell: chsh -s $(which zsh)
  tags:
    - zsh
    - ubuntu
    - wsl
- name: Remove existing .oh-my-zsh directory if it exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
    state: absent
  tags:
    - zsh
    - ubuntu
    - wsl
- name: Install ohmyzsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags:
    - zsh
    - ubuntu
    - wsl
- name: Install zsh plugin autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh
    - ubuntu
    - wsl
- name: Configure zsh plugins
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    regexp: '^plugins='
    line: plugins=(git zsh-autosuggestions pyenv fzf)
  tags:
    - zsh
    - ubuntu
    - wsl
